
version: 2

models:
  - name: stg_customer
    description: "Staging model for the customer dimension"
    columns:
      - name: CUSTOMER_ID
        description: "The customer identifier. Primary key."
        data_tests:
          - unique
          - not_null
      - name: FULL_NAME
        description: "Customer name"
        data_tests:
          - not_null
          - unique
      - name: COUNTRY
        description: "Customer origin country"
      - name: EMAIL
        description: "Customer email"
        data_tests:
          - unique
      - name: PREFERRED_CUSTOMER
        description: "Y if the customer is loyal"
        data_tests:
          - not_null
  - name: stg_store
    description: "Staging model for the store dimension"
    columns:
      - name: STORE_ID
        description: "Store Unique Identifier"
        data_tests:
          - not_null
          - unique
      - name: NAME
        description: "Store name"
      - name: MANAGER
        description: "Store manager"
      - name: NUMBER_EMPLOYEES
        description: "Number of people working in the store"
        data_tests:
          - is_not_negative
      - name: HOURS
        description: "When the store is open"
      - name: CITY
        description: "Which city the store is at"
      - name: COUNTY
        description: "Which county the store is at"
      - name: STATE
        description: "Which state the store is at"
      - name: STREET
        description: "Which street the store is at"
  - name: stg_promotion
    description: "Staging model for the table promotion"
    columns:
      - name: PROMO_ID
        description: "Promotion unique Identifier"
        data_tests:
          - not_null
      - name: ITEM
        description: "Item in promotion"
      - name: COST
        description: "The cost of the product with the current promotion"
        data_tests:
          - is_not_negative
      - name: NAME
        description: "Promotion name"
      - name: DISCOUNT_ACTIVE
        description: "Indicates if the promotion is currently available"
      - name: UPDATED_AT
        description: "When the promotion was modified in the source system."
      - name: VALID_FROM
        description: "From when the current values for the promotion were valid"
      - name: VALID_TO
        description: "Until when the current values for the promotion were valid"
  - name: stg_item
    description: "Available items for sale"
    columns:
      - name: ITEM_ID
        description: "Item identifier in the source system. May be duplicated in this model."
        data_tests:
          - not_null
      - name: NAME
        description: "Item name"
      - name: CURRENT_PRICE
        description: "Current price for the item"
        data_tests:
          - is_not_negative
          - not_null
      - name: WHOLESALE_COST
        description: "Wholesale cost for the item"
        data_tests:
          - is_not_negative
      - name: SIZE
        description: "Item size"
      - name: COLOR
        description: "Item color"
      - name: UNITS
        description: "Measure units for the item"
      - name: UPDATED_AT
        description: "When the item was modified in the source system."
      - name: VALID_FROM
        description: "From when the current values for the item were valid"
      - name: VALID_TO
        description: "Until when the current values for the item were valid" 