SELECT
    P_PROMO_SK AS PROMO_ID
    ,P_ITEM_SK ITEM
    ,P_COST COST
    ,P_PROMO_NAME NAME
    ,IFF(P_DISCOUNT_ACTIVE = 'N', 'NO', 'YES') AS DISCOUNT_ACTIVE
    ,DBT_UPDATED_AT UPDATED_AT
    ,DBT_VALID_FROM VALID_FROM
    ,DBT_VALID_TO VALID_TO
FROM {{ ref('promos_snapshot') }}