USE ROLE USERADMIN;


-- Configuring role
CREATE OR REPLACE ROLE DBT_ROLE;
GRANT ROLE SYSADMIN TO ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER DANGIL28;
USE ROLE DBT_ROLE;


-- configuring WHS
CREATE WAREHOUSE DBT_WH
WITH
WAREHOUSE_SIZE = xsmall
AUTO_RESUME = true
AUTO_SUSPEND = 180
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 2;

USE WAREHOUSE DBT_WH;


-- Creating target database
CREATE DATABASE RETAIL_DWH;
CREATE SCHEMA DWH;
USE SCHEMA RETAIL_DWH.DWH;