
version: 2

models:
  - name: dim_customer
    description: "Customer dimension - Business facing"
    columns:
      - name: CUSTOMER_SK
        description: "Customer identifier"
      - name: NAME
        description: "Customer name"
      - name: ORIGIN_COUNTRY
        description: "Customer's country of origin"
      - name: EMAIL
        description: "Customer's email"
      - name: PREFERRED_CUSTOMER
        description: "Y if the customer is loyal"
  - name: dim_store
    description: "Staging model for the store dimension"
    columns:
      - name: STORE_SK
        description: "Store Unique Identifier"
      - name: NAME
        description: "Store name"
      - name: MANAGER
        description: "Store manager"
      - name: NUMBER_EMPLOYEES
        description: "Number of people working in the store"
      - name: HOURS
        description: "When the store is open"
      - name: CITY
        description: "Which city the store is at"
      - name: COUNTY
        description: "Which county the store is at"
      - name: STATE
        description: "Which state the store is at"
      - name: STREET
        description: "Which street the store is at"