USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF100TCL;
SHOW TABLES;
SELECT TOP 10 * FROM STORE_SALES;

USE SCHEMA TPCH_SF1;
SHOW TABLES;
SELECT TOP 10 * FROM ORDERS;

USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;
SELECT TOP 10 * FROM INVENTORY;

SELECT
    TOP 10
    C_CUSTOMER_SK AS CUSTOMER_ID
    ,TRIM(
        REPLACE(
            IFNULL(C_SALUTATION,'') || ' ' ||
            IFNULL(C_FIRST_NAME,'') || ' ' ||
            IFNULL(C_LAST_NAME,'')
        ,'  ','')
    ) AS FULL_NAME
    ,C_BIRTH_COUNTRY AS COUNTRY
    ,C_EMAIL_ADDRESS AS EMAIL
    ,C_PREFERRED_CUST_FLAG AS PREFERRED_CUSTOMER
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;

DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;

select top 10 * from RETAIL_DWH.DWH.STG_CUSTOMER;