version: 2

sources:
  - name: raw
    database: DBT_SAMPLE_RAW_DATA
    schema: RAW
    tables:
      - name: STORE_SALES
      - name: CUSTOMERS
      - name: CUSTOMERS_STREAM
      - name: STORE
      - name: STORE_STREAM
      - name: PROMOTION